run:
  skip-dirs:
  skip-files:

linters-settings:
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
  #  - errcheck
  #  - ineffassign
  #  - gas
    - gofmt
  #  - gosimple
  #  - govet
  #  - lll
  #  - unused
  #  - staticcheck
    - goimports
