run:
  tests: false

linters-settings:
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
#   - errcheck
#   - ineffassign
#   - gas
    - gofmt
#   - golint
    - gosimple
    - govet
    - lll
#   - varcheck
#   - unused
#   - gosec
