name: "🙋 Question"
description: Question related to Badger
title: "[QUESTION]: <Title>"
labels: ["kind/question ", "status/triage"]
body:
  - type: markdown
    attributes:
      value: |
        The issue tracker is primarily for code related issues, bug reports, missing documentation, or feature requests.
        - If you have a question, please consider asking it on https://discuss.dgraph.io
  - type: textarea
    attributes:
      label: Question.
      description: Ask your Question.
