name: cd-badger
on: workflow_dispatch
jobs:
  badger-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Set Badger Release Version
        run: |
          #!/bin/bash
          GIT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$GIT_BRANCH_NAME" == "release/v"* ]]; 
          then
            echo "this is a release branch"
          else
            echo "this is NOT a release branch"
            exit 1
          fi
          BADGER_RELEASE_VERSION=$(git rev-parse --abbrev-ref HEAD | sed  's/release\///')
          echo "making a new release for "$BADGER_RELEASE_VERSION
          echo "BADGER_RELEASE_VERSION=$BADGER_RELEASE_VERSION" >> $GITHUB_ENV
      - name: Build badger linux/amd64
        run: make badger
      - name: Generate SHA for Linux Build
        run: cd badger && sha256sum badger-linux-amd64 | cut -c-64 > badger-checksum-linux-amd64.sha256
      - name: Tar Archive for Linux Build
        run: cd badger && tar -zcvf badger-linux-amd64.tar.gz badger-linux-amd64
      - name: Upload Badger Binary Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            badger/badger-checksum-linux-amd64.sha256
            badger/badger-linux-amd64.tar.gz
