name: cd-badger

on:
  workflow_dispatch:
    inputs:
      releasetag:
        description: releasetag
        required: true
        type: string

permissions:
  contents: read

jobs:
  badger-build-amd64:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.inputs.releasetag }}"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set Badger Release Version
        run: |
          #!/bin/bash
          GIT_TAG_NAME='${{ github.event.inputs.releasetag }}'
          if [[ "$GIT_TAG_NAME" == "v"* ]];
          then
            echo "this is a release tag"
          else
            echo "this is NOT a release tag"
            exit 1
          fi
          BADGER_RELEASE_VERSION='${{ github.event.inputs.releasetag }}'
          echo "making a new release for "$BADGER_RELEASE_VERSION
          echo "BADGER_RELEASE_VERSION=$BADGER_RELEASE_VERSION" >> $GITHUB_ENV
      - name: Fetch dependencies
        run: sudo apt-get update && sudo apt-get -y install build-essential
      - name: Build badger linux/amd64
        run: make badger
      - name: Generate SHA for Linux Build
        run:
          cd badger && sha256sum badger-linux-amd64 | cut -c-64 > badger-checksum-linux-amd64.sha256
      - name: Tar Archive for Linux Build
        run: cd badger && tar -zcvf badger-linux-amd64.tar.gz badger-linux-amd64
      - name: Upload Badger Binary Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: badger-linux-amd64-${{ github.run_id }}-${{ github.job }}
          path: |
            badger/badger-checksum-linux-amd64.sha256
            badger/badger-linux-amd64.tar.gz

  badger-build-arm64:
    runs-on: warp-ubuntu-latest-arm64-4x
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.inputs.releasetag }}"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set Badger Release Version
        run: |
          #!/bin/bash
          GIT_TAG_NAME='${{ github.event.inputs.releasetag }}'
          if [[ "$GIT_TAG_NAME" == "v"* ]];
          then
            echo "this is a release tag"
          else
            echo "this is NOT a release tag"
            exit 1
          fi
          BADGER_RELEASE_VERSION='${{ github.event.inputs.releasetag }}'
          echo "making a new release for "$BADGER_RELEASE_VERSION
          echo "BADGER_RELEASE_VERSION=$BADGER_RELEASE_VERSION" >> $GITHUB_ENV
      - name: Fetch dependencies
        run: sudo apt-get -y install build-essential
      - name: Build badger linux/arm64
        run: make badger
      - name: Generate SHA for Linux Build
        run:
          cd badger && sha256sum badger-linux-arm64 | cut -c-64 > badger-checksum-linux-arm64.sha256
      - name: Tar Archive for Linux Build
        run: cd badger && tar -zcvf badger-linux-arm64.tar.gz badger-linux-arm64
      - name: List Artifacts
        run: ls -al badger/
      - name: Upload Badger Binary Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: badger-linux-arm64-${{ github.run_id }}-${{ github.job }}
          path: |
            badger/badger-checksum-linux-arm64.sha256
            badger/badger-linux-arm64.tar.gz
