name: ci-aqua-security-trivy-tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/*'
      - 'docs/**'
      - 'images/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  security-events: write

jobs:
  build:
    name: trivy-tests
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'          
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
