name: ci-badger-bank-tests
on:
  push:
    branches:
      - main
      - release/v3.2103
      - release/v4.0
  pull_request:
    branches:
      - main
      - release/v3.2103
      - release/v4.0
  schedule:
    - cron: "*/30 * * * *"
jobs:
  badger-bank:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get Go Version
        run: |
          #!/bin/bash
          DEFAULT_VERSION="1.19"
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; } || echo $DEFAULT_VERSION)
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Install Dependencies
        run: make dependency
      - name: Install jemalloc
        run: make jemalloc
      - name: Install Badger
        run: cd badger && go install --race --tags=jemalloc .
      - name: Run Badger Bank Test
        run: |
          #!/bin/bash
          mkdir bank && cd bank
          badger bank test -v --dir=. -d=20m
