name: ci-badger-tests-coverage
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/*'
      - 'docs/**'
      - 'images/**'
    branches:
      - main
      - 'release/v*'
jobs:
  badger-tests-coverage:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4 # checkout merge commit
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Install Dependencies
        run: make dependency
      - name: Run Badger Tests
        run: make test
      - name: Install Goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send Coverage Results
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLSIO_TOKEN }}
        run: goveralls -coverprofile=cover.out
