name: ci-golang-lint
on:
  pull_request:
    branches:
      - main
      - 'release/v*'
jobs:
  go-lint:
    name: lint
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVERSION }}
      - name: golang-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          only-new-issues: true
          args: --timeout=10m
          skip-pkg-cache: true
          skip-build-cache: true
