name: ci-golang-lint
on:
  push:
    branches:
      - main
      - 'release/v*'
  pull_request:
    branches:
      - main
      - 'release/v*'
  schedule:
    - cron: "*/30 * * * *"
jobs:
  go-lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: golang-lint
        env:
          # prevent OOM
          GOGC: 10
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.48
          only-new-issues: true
          args: --timeout=10m
