name: ci-golang-lint
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/*'
      - 'docs/**'
      - 'images/**'
    branches:
      - main
      - 'release/v*'
jobs:
  go-lint:
    name: lint
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: golang-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          only-new-issues: true
          args: --timeout=10m
          skip-cache: true
